### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ejgallego** [ezgicicek/BiRelCost#1]
Dear Ezgi,

the software contained in this repository and in https://github.com/ezgicicek/bi_relcost does seem to contain code from https://github.com/ejgallego/HOARe2 and/or https://github.com/ejgallego/dfuzz

In accordance with the [LICENSE](https://github.com/ejgallego/HOARe2/blob/master/LICENSE) file of the aforementioned software:
```
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
```
which so far is not met by this repos; note that you don't have to license the code in any particular way; however reproduction of the original notice is indeed required by the licence.

Let me know if you have any question or I can be of help [but I'm afraid that given the list of copyright holders there is not much choice on what to do here]

Best regards!
Emilio

**Comment by ejgallego** [comment]
The easiest way to close this issue is just to add this [LICENSE](https://github.com/ejgallego/HOARe2/blob/master/LICENSE) file to the repository extending the list of copyright holders as it does correspond.

**Comment by ezgicicek** [comment]
Dear Emilio,
Thank you so much for bringing this to my attention and sorry for my late reply since this seems to land in my spam folder.  I should have put the copyright statement from DFuzz repository which some parts of this code is based on. I have added the license file now.

Best,
Ezgi

**Comment by ejgallego** [comment]
Thanks @ezgicicek , and sorry to bother you with such annoying bureaucracy.

By the way, IMO you may want to update the LICENSE to add your own (c):
```
Copyright (c) 2014, The Trustees of the University of Pennsylvania
Copyright (c) 2019, Ezgi Çiçek / Max Plank / whatever
```

Best regards, E.
